# vim: set ft=yaml ts=2 sw=2 expandtab:
# On GHA, the Linux runners are *much* faster and more reliable, so we only run the full matrix build there
name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '05 17 15 * *'  # 15th of the month at 5:05pm UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux-build-and-test:
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-build-and-test.yml@v2
    secrets: inherit
    with:
      matrix-os-version: "[ 'ubuntu-latest' ]"
      matrix-python-version: "[ '3.7', '3.8', '3.9', '3.10', '3.11' ]"  # run Linux tests on all supported Python versions
      poetry-version: "1.3.1"
      enable-coveralls: true  # only report to coveralls.io for tests that run on Linux
  macos-build-and-test:
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-build-and-test.yml@v2
    secrets: inherit
    with:
      matrix-os-version: "[ 'macos-latest' ]"
      matrix-python-version: "[ '3.11' ]"  # only run MacOS tests on latest Python
      poetry-version: "1.3.1"
      enable-coveralls: false 
  windows-build-and-test:
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-build-and-test.yml@v2
    secrets: inherit
    with:
      matrix-os-version: "[ 'windows-latest' ]"
      matrix-python-version: "[ '3.11' ]"  # only run Windows tests on latest Python
      poetry-version: "1.3.1"
      enable-coveralls: false 
